name: networker_s5
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'
dependencies: 
  networker:
    path: ../networker
  s5: ^0.2.0
  hive: ^2.2.3
  http: ^1.2.0
dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.9
