name: networker_s5
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'
dependencies: 
  networker:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      path: packages/networker/networker
      ref: 6617b9bbfb481ef59b1a6921f1676bb90d73ecf9
  lib5:
    git: https://github.com/s5-dev/lib5
  lib5_crypto_implementation_dart: ^0.1.0
  hive: ^2.2.3
  http: ^1.2.0
dependency_overrides: 
  lib5:
    git: https://github.com/s5-dev/lib5

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
