name: networker_rtc
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'
dependencies: 
  flutter_webrtc: ^0.9.42+hotfix.1
  networker:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      path: packages/networker/networker
      ref: c829dc971ee98519ee778d289bae9c413da68376

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.0
