name: networker_rtc
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'
dependencies: 
  flutter_webrtc: ^0.10.6
  networker:
    path: ../networker

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.9
