name: networker_rtc
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'
dependencies: 
  flutter_webrtc: ^0.9.42+hotfix.1
  networker:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      path: packages/networker/networker
      ref: 51e8e6e0f3531c35f9d4f34f04ac1235e74fea9b

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
