name: networker_rtc
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'
dependencies: 
  flutter_webrtc: ^0.10.6
  networker:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      path: packages/networker/networker
      ref: 6617b9bbfb481ef59b1a6921f1676bb90d73ecf9

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.9
