name: networker_rtc
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ">=2.19.0 <3.0.0"
dependencies:
  flutter_webrtc: ^0.12.1+hotfix.1
  networker:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs
      path: packages/networker/networker
      ref: e73c752d745273d80d8dcb51bd14f4e9595005e2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.9
