name: networker_rtc
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ">=2.19.0 <3.0.0"
dependencies:
  flutter_webrtc: ^0.12.1+hotfix.1
  networker:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      path: packages/networker/networker
      ref: cae5eb2c970b704c1c07b046ffe338500c6fe08d

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.9
