name: lw_file_system
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  archive: ^3.6.0
  collection: ^1.18.0
  dart_mappable: ^4.2.2
  idb_shim: ^2.4.1+1
  rxdart: ^0.27.7
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.10
  dart_mappable_builder: ^4.2.3
  lints: ^3.0.0
  test: ^1.24.0
