[package]
name = "flutter_onenote"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.7.0"
onenote_parser = { git = "https://github.com/CodeDoctorDE/onenote.rs", rev = "29c08532252b917543ff268284f926f30876bb79" }
