name: example
description: A basic pure-dart web app with ssr & automatic client hydration.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  jaspr: ^0.8.2
  web_leap:
    path: ../

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  jaspr_builder: ^0.8.2
  lints: ^2.1.0
