name: material_leap
description: Additional widgets for Flutter Material Design.
version: 0.0.1
publish_to: none
source: https://github.com/LinwoodDev/material_leap

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  intl: ^0.18.0
  flutter_localizations:
    sdk: flutter
  phosphor_flutter:
    git:
      url: https://github.com/CodeDoctorDE/phosphor-flutter
      ref: f370dd2c25d3ea51ffb8f1c7c183bc9f33889c82
  flutter:
    sdk: flutter
  dart_leap:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs
      path: packages/dart_leap
      ref: 47a223756447b027f6e0d2f7e537f4a1ca4bbce7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
