name: networker_socket
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'
dependencies: 
  networker:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      path: packages/networker/networker
      ref: fa684323b993e73514da2bc1497e25c9e6323c0a
  web_socket_channel: ^2.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
