name: networker_socket
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  networker:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs
      path: packages/networker/networker
      ref: 84a54efe5351072d2f520de619a0f4270c407b2d
  web_socket_channel: ^3.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.9
