name: networker_socket
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ">=2.19.0 <4.0.0"
dependencies:
  networker:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs
      path: packages/networker/networker
      ref: 4d8b20841bcfa644695963c69f3e3032b764d283
  web_socket_channel: ^3.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.9
