name: networker_socket
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ">=2.19.0 <4.0.0"
dependencies:
  networker:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      path: packages/networker/networker
      ref: e19c3a25196ddbe2517e99bffce951164415a4d3
  web_socket_channel: ^3.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.9
