name: networker_socket
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'
dependencies: 
  networker:
    git:
      url: https://github.com/LinwoodDev/dart_pkgs.git
      path: packages/networker/networker
      ref: 6617b9bbfb481ef59b1a6921f1676bb90d73ecf9
  web_socket_channel: ^2.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
